"""added wind

Revision ID: 0471baa5fa01
Revises: 45004ffd5a84
Create Date: 2019-12-31 01:38:49.485337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0471baa5fa01'
down_revision = '45004ffd5a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ms', sa.Float(), nullable=False),
    sa.Column('kmph', sa.Float(), nullable=False),
    sa.Column('mph', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wind')
    # ### end Alembic commands ###
