"""added fields to DHT

Revision ID: 096c64011b6b
Revises: fadbe686033c
Create Date: 2019-10-15 22:24:49.464701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '096c64011b6b'
down_revision = 'fadbe686033c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DHT', sa.Column('heat_index_c', sa.Float(), nullable=False))
    op.add_column('DHT', sa.Column('heat_index_f', sa.Float(), nullable=False))
    op.add_column('DHT', sa.Column('temperature_c', sa.Float(), nullable=False))
    op.add_column('DHT', sa.Column('temperature_f', sa.Float(), nullable=False))
    op.drop_column('DHT', 'temperature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DHT', sa.Column('temperature', mysql.FLOAT(), nullable=False))
    op.drop_column('DHT', 'temperature_f')
    op.drop_column('DHT', 'temperature_c')
    op.drop_column('DHT', 'heat_index_f')
    op.drop_column('DHT', 'heat_index_c')
    # ### end Alembic commands ###
