"""added tables

Revision ID: 45004ffd5a84
Revises:
Create Date: 2019-10-30 23:57:03.952344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45004ffd5a84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fc37',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('rain', sa.CHAR(length=1), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('heat_index',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('celsius', sa.Float(), nullable=False),
                    sa.Column('fahrenheit', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('celsius', 'fahrenheit', name='unique_heat_index'))
    op.create_table('pressure',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('pascal', sa.Float(), nullable=False),
                    sa.Column('kilopascal', sa.Float(), nullable=False),
                    sa.Column('mbar', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('pascal', 'kilopascal', 'mbar', name='unique_pressure'))
    op.create_table('station',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('lat', sa.Float(), nullable=False),
                    sa.Column('lng', sa.Float(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('temperature',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('celsius', sa.Float(), nullable=False),
                    sa.Column('fahrenheit', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('celsius', 'fahrenheit', name='unique_temperature'))
    op.create_table('temt6000',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('lux', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('averages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('temperature_id', sa.Integer(), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['temperature_id'], ['temperature.id'], ),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('bme280',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('temperature_id', sa.Integer(), nullable=True),
                    sa.Column('humidity', sa.Float(), nullable=False),
                    sa.Column('pressure_id', sa.Integer(), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['pressure_id'], ['pressure.id'], ),
                    sa.ForeignKeyConstraint(['temperature_id'], ['temperature.id'], ),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('dht',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('station_id', sa.Integer(), nullable=True),
                    sa.Column('temperature_id', sa.Integer(), nullable=True),
                    sa.Column('humidity', sa.Float(), nullable=False),
                    sa.Column('heat_index_id', sa.Integer(), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['heat_index_id'], ['heat_index.id'], ),
                    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
                    sa.ForeignKeyConstraint(['temperature_id'], ['temperature.id'], ),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('ds18b20',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('temperature_id', sa.Integer(), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['temperature_id'], ['temperature.id'], ),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ds18b20')
    op.drop_table('dht')
    op.drop_table('bme280')
    op.drop_table('averages')
    op.drop_table('temt6000')
    op.drop_table('temperature')
    op.drop_table('station')
    op.drop_table('pressure')
    op.drop_table('heat_index')
    op.drop_table('fc37')
    # ### end Alembic commands ###
