"""added sensors

Revision ID: 6b4468c03280
Revises: 096c64011b6b
Create Date: 2019-10-25 14:29:14.978345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b4468c03280'
down_revision = '096c64011b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('f_c37',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('rain', sa.CHAR(length=1), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))

    op.create_table('heat_index',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('celsius', sa.Float(), nullable=False),
                    sa.Column('fahrenheit', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('celsius', 'fahrenheit', name='unique_heat_index'))
    op.create_table('tem_t6000',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('lux', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('temperature',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('celsius', sa.Float(), nullable=False),
                    sa.Column('fahrenheit', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('celsius', 'fahrenheit', name='unique_temperature'))
    op.create_table('averages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('temperature_id', sa.Integer(), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['temperature_id'], ['temperature.id'], ),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('bm_e280',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('temperature_id', sa.Integer(), nullable=True),
                    sa.Column('humidity', sa.Float(), nullable=False),
                    sa.Column('pressure', sa.Float(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['temperature_id'], ['temperature.id'], ),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('d_s18_b20',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('temperature_id', sa.Integer(), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['temperature_id'], ['temperature.id'], ),
                    sa.PrimaryKeyConstraint('id'))
    op.add_column('DHT', sa.Column('heat_index_id', sa.Integer(), nullable=True))
    op.add_column('DHT', sa.Column('temperature_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'DHT', 'heat_index', ['heat_index_id'], ['id'])
    op.create_foreign_key(None, 'DHT', 'temperature', ['temperature_id'], ['id'])
    op.drop_column('DHT', 'temperature_c')
    op.drop_column('DHT', 'heat_index_c')
    op.drop_column('DHT', 'heat_index_f')
    op.drop_column('DHT', 'temperature_f')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DHT', sa.Column('temperature_f', mysql.FLOAT(), nullable=False))
    op.add_column('DHT', sa.Column('heat_index_f', mysql.FLOAT(), nullable=False))
    op.add_column('DHT', sa.Column('heat_index_c', mysql.FLOAT(), nullable=False))
    op.add_column('DHT', sa.Column('temperature_c', mysql.FLOAT(), nullable=False))
    op.drop_constraint(None, 'DHT', type_='foreignkey')
    op.drop_constraint(None, 'DHT', type_='foreignkey')
    op.drop_column('DHT', 'temperature_id')
    op.drop_column('DHT', 'heat_index_id')
    op.drop_table('d_s18_b20')
    op.drop_table('bm_e280')
    op.drop_table('averages')
    op.drop_table('temperature')
    op.drop_table('tem_t6000')
    op.drop_table('heat_index')
    op.drop_table('f_c37')
    # ### end Alembic commands ###
