"""added tables for dht sensor
Revision ID: fadbe686033c
Revises:
Create Date: 2019-10-02 19:53:26.677172
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fadbe686033c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('lat', sa.Float(), nullable=False),
                    sa.Column('lng', sa.Float(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('DHT',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('station_id', sa.Integer(), nullable=True),
                    sa.Column('temperature', sa.Float(), nullable=False),
                    sa.Column('humidity', sa.Float(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DHT')
    op.drop_table('station')
    # ### end Alembic commands ###
